### ISSUE TITLE
Tables and Photos numeric captions 

### ISSUE THREAD

**Issue by rqpe** [Health-Sprints/template#16]
Works depending on which time of export, probably a css issue

**Comment by MurakamiShinyu** [comment]
(An alternative way for numbering without using CSS counters)

If Fidus Writer can put `data-*` attributes for numbering when exporting HTML, the following HTML+CSS will work:

```html
  <figure id="F74305891" data-category="figure"><img src="images/3664e5be-a2b9-4171-afee-fa6cd0086a2d.png">
    <figcaption><span class="label" data-cat-figure-num="51">Figure</span><span class="text">Components of management</span></figcaption>
  </figure>
```

```css
figure[data-category='figure'] figcaption span.label[data-cat-figure-num]::after {
    content: ' ' attr(data-cat-figure-num);
}
```

Test JSBin: https://jsbin.com/zadedoc/edit?html,css,output
with Vivliostyle: https://vivliostyle.vercel.app/#src=https://jsbin.com/zadedoc
